name: api
services:
  mutants:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:6666
    depends_on:
      - cache
    links:
      - cache
    networks:
      red:
        ipv4_address: 172.20.0.2

  cache:
    image: redis
    networks:
      red:
        ipv4_address: 172.20.0.3

networks:
  red:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16